[sssd]
config_file_version = 2
services = nss, pam, autofs
domains = fizyk

[nss]

[pam]

[autofs]

[domain/fizyk]
id_provider = ldap
auth_provider = ldap
autofs_provider = ldap

ldap_schema = rfc2307bis
ldap_autofs_search_base = ou=Automount,ou=fizyk,ou=unixAuth,dc=das,dc=fuw,dc=edu,dc=pl

ldap_uri = ldaps://ccdas1.fuw.edu.pl,ldaps://ccdas2.fuw.edu.pl
ldap_search_base = ou=fizyk,ou=unixAuth,dc=das,dc=fuw,dc=edu,dc=pl

ldap_default_bind_dn = cn=hprxGullZgidWS,ou=IFT,ou=unixFizyk,ou=proxyAgents,dc=das,dc=fuw,dc=edu,dc=pl
ldap_default_authtok_type = password
ldap_default_authtok = CHANGE_ME

ldap_tls_reqcert = demand

# Allow-list: only these users may log in; add Dominika Zgid (dzgid?) once her
# LDAP account is created by OKWF admins
access_provider = simple
simple_allow_users = egull, rfarid, ajazdzewska, amarie, abalbi, jdobrzyniecki

cache_credentials = true
enumerate = false
